# Export the embryonic-leaf Seurat object for Python/scVelo
#
# Expected project structure:
# data/
# └── processed/
#     ├── XGE202122_S5_subset_embleaf_harmony_join.rds
#     └── RNA_velocity/
#         └── seurat_export/              # generated by this script
#             ├── counts.mtx
#             ├── features.csv
#             ├── spot_metadata.csv
#             ├── pca.csv
#             ├── umap.csv
#             └── export_manifest.txt
#
# This is Step -1 of the RNA-velocity workflow. It exports the raw RNA UMI
# matrix, spot metadata, PCA coordinates, and the existing Seurat Harmony UMAP
# without using SeuratDisk. The Python workflow reconstructs an AnnData object
# from these files and adds spliced/unspliced layers from data/raw/loom/.

suppressPackageStartupMessages({
  library(Seurat)
  library(SeuratObject)
  library(Matrix)
})

find_project_root <- function(path = getwd()) {
  path <- normalizePath(path, winslash = "/", mustWork = TRUE)
  repeat {
    if (dir.exists(file.path(path, "data")) &&
        dir.exists(file.path(path, "scripts"))) {
      return(path)
    }
    parent <- dirname(path)
    if (identical(parent, path)) {
      stop("Project root not found. Start R in the repository or a subdirectory.")
    }
    path <- parent
  }
}

get_joined_rna_counts <- function(seurat_object) {
  if (!"RNA" %in% SeuratObject::Assays(seurat_object)) {
    stop("The Seurat object does not contain an RNA assay.")
  }

  count_layers <- grep(
    "^counts($|\\.)",
    SeuratObject::Layers(seurat_object[["RNA"]]),
    value = TRUE
  )
  if (length(count_layers) == 0L) {
    stop("The RNA assay does not contain a raw-count layer.")
  }

  if (length(count_layers) > 1L) {
    message("Joining ", length(count_layers), " RNA count layers for export.")
    seurat_object[["RNA"]] <- SeuratObject::JoinLayers(
      seurat_object[["RNA"]],
      layers = count_layers,
      new = "counts"
    )
    count_layer <- "counts"
  } else {
    count_layer <- count_layers[[1L]]
  }

  counts <- SeuratObject::LayerData(
    seurat_object,
    assay = "RNA",
    layer = count_layer
  )
  counts <- counts[, colnames(seurat_object), drop = FALSE]
  if (!inherits(counts, "sparseMatrix")) counts <- as(counts, "dgCMatrix")

  list(object = seurat_object, counts = counts)
}

get_umap_coordinates <- function(seurat_object) {
  reductions <- SeuratObject::Reductions(seurat_object)
  preferred <- c(
    "umap.harmony", "umapharmony", "harmony.umap", "umap",
    reductions[grepl("umap", reductions, ignore.case = TRUE)]
  )
  preferred <- unique(preferred[preferred %in% reductions])
  if (length(preferred) > 0L) {
    reduction <- preferred[[1L]]
    coordinates <- SeuratObject::Embeddings(seurat_object, reduction = reduction)
    if (ncol(coordinates) < 2L) {
      stop("Reduction '", reduction, "' has fewer than two dimensions.")
    }
    coordinates <- coordinates[colnames(seurat_object), 1:2, drop = FALSE]
    storage.mode(coordinates) <- "double"
    colnames(coordinates) <- c("UMAP_1", "UMAP_2")
    attr(coordinates, "source") <- reduction
    return(coordinates)
  }

  metadata <- seurat_object[[]]
  metadata_candidates <- list(
    c("UMAP_1", "UMAP_2"),
    c("umap_1", "umap_2"),
    c("harmonyUMAP_1", "harmonyUMAP_2")
  )
  for (columns in metadata_candidates) {
    if (!all(columns %in% colnames(metadata))) next
    coordinates <- as.matrix(metadata[, columns, drop = FALSE])
    storage.mode(coordinates) <- "double"
    if (all(is.finite(coordinates))) {
      rownames(coordinates) <- colnames(seurat_object)
      colnames(coordinates) <- c("UMAP_1", "UMAP_2")
      attr(coordinates, "source") <- paste(columns, collapse = ",")
      return(coordinates)
    }
  }

  stop("No two-dimensional UMAP coordinates were found in reductions or metadata.")
}

get_pca_coordinates <- function(seurat_object) {
  reductions <- SeuratObject::Reductions(seurat_object)
  preferred <- c("pca", "harmony", reductions[grepl("pca", reductions, ignore.case = TRUE)])
  preferred <- unique(preferred[preferred %in% reductions])
  if (length(preferred) == 0L) return(NULL)

  reduction <- preferred[[1L]]
  coordinates <- SeuratObject::Embeddings(seurat_object, reduction = reduction)
  coordinates <- coordinates[colnames(seurat_object), , drop = FALSE]
  storage.mode(coordinates) <- "double"
  colnames(coordinates) <- paste0("PC_", seq_len(ncol(coordinates)))
  attr(coordinates, "source") <- reduction
  coordinates
}

project_root <- find_project_root()
input_rds <- file.path(
  project_root,
  "data", "processed", "XGE202122_S5_subset_embleaf_harmony_join.rds"
)
output_dir <- file.path(
  project_root, "data", "processed", "RNA_velocity", "seurat_export"
)
session_dir <- file.path(project_root, "results", "sessionInfo")
domain_levels <- c("SAM", "P1_P2", "P3", "P4", "P5")
biological_replicate_levels <- c(
  "UL01", "UL02", "UL04", "VR01", "VR02", "VR03", "VR04",
  "DQ01", "DQ02", "DQ03", "DQ04", "DQ06", "DQ07", "DQ08"
)

if (!file.exists(input_rds)) stop("Input Seurat RDS not found: ", input_rds)
dir.create(output_dir, recursive = TRUE, showWarnings = FALSE)
dir.create(session_dir, recursive = TRUE, showWarnings = FALSE)

message("Reading Seurat object: ", input_rds)
seurat_object <- readRDS(input_rds)
idents_before <- SeuratObject::Idents(seurat_object)

metadata <- seurat_object[[]]
domain_candidates <- c("domains", "domain", "structural_domain")
domain_column <- domain_candidates[domain_candidates %in% colnames(metadata)][1L]
if (is.na(domain_column)) {
  stop(
    "Could not identify a structural-domain column. Available metadata: ",
    paste(colnames(metadata), collapse = ", ")
  )
}
if (!all(c("sample_id", "sample") %in% colnames(metadata))) {
  stop(
    "The embryonic-leaf Seurat metadata must contain both `sample_id` ",
    "(section ID) and `sample` (biological replicate)."
  )
}

keep_spots <- colnames(seurat_object)[
  as.character(metadata[[domain_column]]) %in% domain_levels
]
if (length(keep_spots) == 0L) stop("No SAM/P1_P2/P3/P4/P5 spots were found.")
if (length(keep_spots) < ncol(seurat_object)) {
  message("Subsetting to ", length(keep_spots), " unambiguous SAM-P5 spots.")
  seurat_object <- subset(seurat_object, cells = keep_spots)
  idents_before <- idents_before[keep_spots]
}

count_result <- get_joined_rna_counts(seurat_object)
seurat_object <- count_result$object
counts <- count_result$counts
rm(count_result)

if (anyDuplicated(colnames(counts))) stop("Duplicated spot identifiers were found.")
if (anyDuplicated(rownames(counts))) stop("Duplicated gene identifiers were found.")
if (!identical(colnames(counts), colnames(seurat_object))) {
  stop("RNA count columns do not match the Seurat spot order.")
}

metadata <- seurat_object[[]]
metadata$barcode <- colnames(seurat_object)
metadata$section_id <- as.character(metadata$sample_id)
metadata$biological_replicate <- as.character(metadata$sample)
if (!all(metadata$biological_replicate %in% biological_replicate_levels)) {
  stop(
    "The `sample` column does not contain the expected biological-replicate ",
    "IDs. Values: ",
    paste(unique(metadata$biological_replicate), collapse = ", ")
  )
}
if (anyNA(metadata$section_id) || any(metadata$section_id == "")) {
  stop("The section-level `sample_id` column contains missing or empty values.")
}
metadata$domains <- factor(
  as.character(metadata[[domain_column]]),
  levels = domain_levels,
  ordered = TRUE
)
metadata <- metadata[colnames(seurat_object), , drop = FALSE]
metadata <- data.frame(
  barcode = colnames(seurat_object),
  metadata[, setdiff(colnames(metadata), "barcode"), drop = FALSE],
  check.names = FALSE,
  stringsAsFactors = FALSE
)

umap <- get_umap_coordinates(seurat_object)
umap_source <- attr(umap, "source")
pca <- get_pca_coordinates(seurat_object)
pca_source <- if (is.null(pca)) "not available" else attr(pca, "source")

Matrix::writeMM(counts, file.path(output_dir, "counts.mtx"))
write.csv(
  data.frame(gene_id = rownames(counts), stringsAsFactors = FALSE),
  file.path(output_dir, "features.csv"),
  row.names = FALSE,
  quote = FALSE
)
write.csv(
  metadata,
  file.path(output_dir, "spot_metadata.csv"),
  row.names = FALSE,
  quote = TRUE
)
write.csv(
  data.frame(barcode = rownames(umap), umap, check.names = FALSE),
  file.path(output_dir, "umap.csv"),
  row.names = FALSE,
  quote = FALSE
)
if (!is.null(pca)) {
  write.csv(
    data.frame(barcode = rownames(pca), pca, check.names = FALSE),
    file.path(output_dir, "pca.csv"),
    row.names = FALSE,
    quote = FALSE
  )
}

manifest <- c(
  paste0("input_rds=", normalizePath(input_rds, winslash = "/")),
  paste0("n_genes=", nrow(counts)),
  paste0("n_spots=", ncol(counts)),
  paste0("domain_column=", domain_column),
  paste0("domains=", paste(domain_levels, collapse = ",")),
  "section_id_source=sample_id",
  "biological_replicate_source=sample",
  paste0("umap_source=", umap_source),
  paste0("pca_source=", pca_source),
  "count_assay=RNA",
  "count_layer=raw counts"
)
writeLines(manifest, file.path(output_dir, "export_manifest.txt"))
writeLines(
  capture.output(sessionInfo()),
  file.path(session_dir, "08_RNA_velocity_Seurat_export_sessionInfo.txt")
)

stopifnot(identical(
  as.character(SeuratObject::Idents(seurat_object)),
  as.character(idents_before)
))

message("Seurat export completed: ", output_dir)
message("Exported ", nrow(counts), " genes x ", ncol(counts), " spots.")
message("Biological replicate source: sample")
message("Physical section source: sample_id")
message("UMAP source: ", umap_source)
message("PCA source: ", pca_source)
