# Prepare and integrate the maize shoot scRNA-seq reference in Seurat v5
#
# SRA reference libraries:
#   SRR11943512
#   SRR11943513
#
# Expected project structure:
# data/
# ├── raw/
# │   └── scRNA_reference/
# │       ├── SRR11943512/
# │       │   └── filtered_feature_bc_matrix/
# │       │       ├── matrix.mtx.gz
# │       │       ├── barcodes.tsv.gz
# │       │       └── features.tsv.gz
# │       └── SRR11943513/
# │           └── filtered_feature_bc_matrix/
# │               ├── matrix.mtx.gz
# │               ├── barcodes.tsv.gz
# │               └── features.tsv.gz
# └── processed/
#     └── sc_merged_filter_SCT2_inte.rds       # generated by this script
#
# The script expects downloaded and quantified 10x-style raw gene-count
# matrices. SRA FASTQ download and read alignment are intentionally kept outside
# this R analysis so that external shell commands are not mixed into the R code.

suppressPackageStartupMessages({
  library(Seurat)
  library(SeuratObject)
  library(SingleCellExperiment)
  library(scDblFinder)
  library(glmGamPoi)
  library(harmony)
  library(Matrix)
  library(dplyr)
  library(ggplot2)
  library(patchwork)
})

# -----------------------------
# 1. Paths and parameters
# -----------------------------

find_project_root <- function(path = getwd()) {
  path <- normalizePath(path, winslash = "/", mustWork = TRUE)
  repeat {
    if (dir.exists(file.path(path, "data")) &&
        dir.exists(file.path(path, "scripts"))) {
      return(path)
    }
    parent <- dirname(path)
    if (identical(parent, path)) {
      stop("Project root not found. Start R in the repository or a subdirectory.")
    }
    path <- parent
  }
}

project_root <- find_project_root()
raw_reference_dir <- file.path(project_root, "data", "raw", "scRNA_reference")
processed_dir <- file.path(project_root, "data", "processed")
table_dir <- file.path(
  project_root, "results", "tables", "10_scRNA_reference_integration"
)
figure_dir <- file.path(
  project_root, "results", "figures", "10_scRNA_reference_integration"
)
session_dir <- file.path(project_root, "results", "sessionInfo")

dir.create(processed_dir, recursive = TRUE, showWarnings = FALSE)
dir.create(table_dir, recursive = TRUE, showWarnings = FALSE)
dir.create(figure_dir, recursive = TRUE, showWarnings = FALSE)
dir.create(session_dir, recursive = TRUE, showWarnings = FALSE)

output_rds <- file.path(processed_dir, "sc_merged_filter_SCT2_inte.rds")
overwrite_existing_output <- FALSE

sra_runs <- c("SRR11943512", "SRR11943513")
min_cells <- 3L
min_features <- 200L
variable_features <- 3000L
elbow_pcs <- 50L
integration_pcs <- 30L
cluster_resolution <- 2
random_seed <- 2026L

options(future.globals.maxSize = 8 * 1024^3)
set.seed(random_seed)

if (file.exists(output_rds) && !overwrite_existing_output) {
  stop(
    "The final reference already exists and will not be overwritten: ", output_rds,
    "\nSet overwrite_existing_output <- TRUE only when intentionally rebuilding it."
  )
}

# -----------------------------
# 2. Helper functions
# -----------------------------

has_10x_files <- function(path) {
  matrix_present <- any(file.exists(file.path(
    path, c("matrix.mtx", "matrix.mtx.gz")
  )))
  barcode_present <- any(file.exists(file.path(
    path, c("barcodes.tsv", "barcodes.tsv.gz")
  )))
  feature_present <- any(file.exists(file.path(
    path,
    c("features.tsv", "features.tsv.gz", "genes.tsv", "genes.tsv.gz")
  )))
  matrix_present && barcode_present && feature_present
}

find_10x_matrix_directory <- function(reference_root, run_id) {
  run_root <- file.path(reference_root, run_id)
  if (!dir.exists(run_root)) {
    stop(
      "Raw count directory not found for ", run_id, ": ", run_root,
      "\nPlace the 10x-style matrix under data/raw/scRNA_reference/", run_id,
      "/filtered_feature_bc_matrix/."
    )
  }

  preferred <- c(
    file.path(run_root, "filtered_feature_bc_matrix"),
    file.path(run_root, "raw_feature_bc_matrix"),
    file.path(run_root, "outs", "filtered_feature_bc_matrix"),
    file.path(run_root, "outs", "raw_feature_bc_matrix"),
    run_root
  )
  preferred <- preferred[vapply(preferred, has_10x_files, logical(1))]

  if (length(preferred) == 1L) return(preferred)
  if (length(preferred) > 1L) {
    stop(
      "More than one 10x matrix directory was found for ", run_id, ":\n  ",
      paste(preferred, collapse = "\n  ")
    )
  }

  all_directories <- list.dirs(run_root, recursive = TRUE, full.names = TRUE)
  candidates <- all_directories[
    vapply(all_directories, has_10x_files, logical(1))
  ]
  if (length(candidates) != 1L) {
    stop(
      "Expected exactly one 10x matrix directory for ", run_id,
      "; found ", length(candidates), "."
    )
  }
  candidates
}

read_gene_expression_matrix <- function(matrix_directory) {
  # gene.column = 1 retains stable maize gene identifiers and prevents symbol
  # ambiguity when this reference is later compared with the Visium dataset.
  counts <- Read10X(
    data.dir = matrix_directory,
    gene.column = 1,
    unique.features = TRUE,
    strip.suffix = FALSE
  )

  if (is.list(counts)) {
    preferred_names <- c("Gene Expression", "RNA", "gene_expression")
    selected <- intersect(preferred_names, names(counts))
    if (length(selected) == 0L) {
      stop(
        "Read10X returned multiple assays but no Gene Expression matrix: ",
        paste(names(counts), collapse = ", ")
      )
    }
    counts <- counts[[selected[1L]]]
  }

  if (!inherits(counts, "sparseMatrix")) counts <- as(counts, "dgCMatrix")
  counts
}

detect_doublets_and_retain_singlets <- function(seurat_object, run_id) {
  message("Running scDblFinder for ", run_id)
  sce <- as.SingleCellExperiment(seurat_object, assay = "RNA")

  set.seed(random_seed)
  sce <- scDblFinder(
    sce,
    samples = NULL,
    returnType = "sce",
    verbose = TRUE
  )

  seurat_object$scDblFinder.score <- colData(sce)$scDblFinder.score
  seurat_object$scDblFinder.class <- as.character(
    colData(sce)$scDblFinder.class
  )

  class_counts <- as.data.frame(table(
    SRA_run = run_id,
    scDblFinder_class = seurat_object$scDblFinder.class
  ))
  class_counts$before_filtering <- ncol(seurat_object)

  singlets <- colnames(seurat_object)[
    seurat_object$scDblFinder.class == "singlet"
  ]
  if (length(singlets) == 0L) {
    stop("scDblFinder did not retain any singlets for ", run_id)
  }
  seurat_object <- subset(seurat_object, cells = singlets)
  class_counts$singlets_retained <- ncol(seurat_object)

  rm(sce)
  gc(verbose = FALSE)
  list(object = seurat_object, summary = class_counts)
}

load_and_filter_library <- function(run_id) {
  matrix_directory <- find_10x_matrix_directory(raw_reference_dir, run_id)
  message("Reading ", run_id, " from ", matrix_directory)
  counts <- read_gene_expression_matrix(matrix_directory)

  object <- CreateSeuratObject(
    counts = counts,
    project = run_id,
    assay = "RNA",
    min.cells = min_cells,
    min.features = min_features
  )
  object$SRA_run <- run_id
  object$library_id <- run_id
  object$reference_dataset <- "maize_shoot_scRNA"

  detected <- detect_doublets_and_retain_singlets(object, run_id)
  detected$matrix_directory <- matrix_directory
  detected
}

# -----------------------------
# 3. Load the two libraries and remove doublets separately
# -----------------------------

library_results <- lapply(sra_runs, load_and_filter_library)
names(library_results) <- sra_runs

doublet_summary <- bind_rows(lapply(library_results, `[[`, "summary"))
write.csv(
  doublet_summary,
  file.path(table_dir, "scDblFinder_summary_by_library.csv"),
  row.names = FALSE
)

singlet_objects <- lapply(library_results, `[[`, "object")
rm(library_results)
gc(verbose = FALSE)

# Prefix cell names by run so cell identifiers remain globally unique.
singlet_objects <- Map(
  f = function(object, run_id) {
    RenameCells(object, add.cell.id = run_id)
  },
  object = singlet_objects,
  run_id = names(singlet_objects)
)
names(singlet_objects) <- sra_runs

# Merging preserves a separate counts layer for each library in Seurat v5.
sc_reference <- merge(
  x = singlet_objects[[1L]],
  y = singlet_objects[-1L],
  merge.data = FALSE,
  project = "maize_shoot_scRNA_reference"
)
rm(singlet_objects)
gc(verbose = FALSE)

rna_count_layers <- grep(
  "^counts($|\\.)",
  Layers(sc_reference[["RNA"]]),
  value = TRUE
)
if (length(rna_count_layers) != length(sra_runs)) {
  stop(
    "Expected one RNA counts layer per library after merging; found: ",
    paste(rna_count_layers, collapse = ", ")
  )
}

# -----------------------------
# 4. SCTransform v2 with glmGamPoi
# -----------------------------

DefaultAssay(sc_reference) <- "RNA"
set.seed(random_seed)
sc_reference <- SCTransform(
  object = sc_reference,
  assay = "RNA",
  new.assay.name = "SCT",
  vst.flavor = "v2",
  method = "glmGamPoi",
  variable.features.n = variable_features,
  return.only.var.genes = FALSE,
  conserve.memory = TRUE,
  verbose = TRUE
)

DefaultAssay(sc_reference) <- "SCT"

# -----------------------------
# 5. PCA selection and elbow plot
# -----------------------------

# Calculate additional PCs for visual inspection of the elbow. This diagnostic
# reduction is retained separately and is not supplied to Harmony.
set.seed(random_seed)
sc_reference <- RunPCA(
  sc_reference,
  assay = "SCT",
  npcs = elbow_pcs,
  reduction.name = "pca.elbow",
  reduction.key = "PCelbow_",
  verbose = TRUE
)

elbow_plot <- ElbowPlot(
  sc_reference,
  reduction = "pca.elbow",
  ndims = elbow_pcs
) +
  geom_vline(
    xintercept = integration_pcs,
    linetype = "dashed",
    color = "red"
  ) +
  labs(
    title = "PCA elbow plot for the maize scRNA-seq reference",
    subtitle = paste0(
      "The first ", integration_pcs,
      " PCs were retained for Harmony integration"
    )
  ) +
  theme_classic(base_size = 11)

ggsave(
  file.path(figure_dir, "scRNA_reference_PCA_elbow_plot.png"),
  elbow_plot,
  width = 7,
  height = 5,
  dpi = 300
)
ggsave(
  file.path(figure_dir, "scRNA_reference_PCA_elbow_plot.pdf"),
  elbow_plot,
  width = 7,
  height = 5
)

# Recalculate exactly 30 PCs under the canonical reduction name. Harmony will
# therefore receive only these 30 dimensions, independent of whether a Seurat
# release ignores a forwarded dims argument in HarmonyIntegration().
set.seed(random_seed)
sc_reference <- RunPCA(
  sc_reference,
  assay = "SCT",
  npcs = integration_pcs,
  reduction.name = "pca",
  reduction.key = "PC_",
  verbose = TRUE
)

# -----------------------------
# 6. Harmony layer integration
# -----------------------------

set.seed(random_seed)
sc_reference <- IntegrateLayers(
  object = sc_reference,
  method = HarmonyIntegration,
  orig.reduction = "pca",
  new.reduction = "harmony",
  assay = "SCT",
  dims = seq_len(integration_pcs),
  verbose = TRUE
)

if (!"harmony" %in% Reductions(sc_reference)) {
  stop("Harmony integration did not create the 'harmony' reduction.")
}
if (ncol(Embeddings(sc_reference, reduction = "harmony")) < integration_pcs) {
  stop("The Harmony reduction contains fewer than 30 dimensions.")
}

# Rejoin the RNA library layers after integration, as required before later
# differential-expression or reference-comparison analyses. SCTransform creates
# a unified SCT assay; if a future Seurat release retains multiple SCT data
# layers, join those as well.
sc_reference <- JoinLayers(sc_reference, assay = "RNA")
sct_data_layers <- grep(
  "^(counts|data)($|\\.)",
  Layers(sc_reference[["SCT"]]),
  value = TRUE
)
if (length(grep("^data($|\\.)", sct_data_layers)) > 1L ||
    length(grep("^counts($|\\.)", sct_data_layers)) > 1L) {
  sc_reference <- JoinLayers(sc_reference, assay = "SCT")
}

# -----------------------------
# 7. UMAP and graph-based clustering
# -----------------------------

DefaultAssay(sc_reference) <- "SCT"
sc_reference <- FindNeighbors(
  sc_reference,
  reduction = "harmony",
  dims = seq_len(integration_pcs),
  graph.name = c("harmony_nn", "harmony_snn"),
  verbose = TRUE
)

set.seed(random_seed)
sc_reference <- FindClusters(
  sc_reference,
  graph.name = "harmony_snn",
  resolution = cluster_resolution,
  cluster.name = "harmony_clusters",
  random.seed = random_seed,
  verbose = TRUE
)

set.seed(random_seed)
sc_reference <- RunUMAP(
  sc_reference,
  reduction = "harmony",
  dims = seq_len(integration_pcs),
  reduction.name = "umap.harmony",
  reduction.key = "harmonyUMAP_",
  seed.use = random_seed,
  verbose = TRUE
)

Idents(sc_reference) <- "harmony_clusters"

umap_by_library <- DimPlot(
  sc_reference,
  reduction = "umap.harmony",
  group.by = "SRA_run",
  shuffle = TRUE
) +
  ggtitle("Maize scRNA-seq reference: two integrated libraries")

umap_by_cluster <- DimPlot(
  sc_reference,
  reduction = "umap.harmony",
  group.by = "harmony_clusters",
  label = TRUE,
  repel = TRUE
) +
  ggtitle(paste0("Harmony clusters (resolution = ", cluster_resolution, ")"))

integration_figure <- umap_by_library | umap_by_cluster
ggsave(
  file.path(figure_dir, "scRNA_reference_Harmony_UMAP.png"),
  integration_figure,
  width = 12,
  height = 5.5,
  dpi = 300
)
ggsave(
  file.path(figure_dir, "scRNA_reference_Harmony_UMAP.pdf"),
  integration_figure,
  width = 12,
  height = 5.5
)

# -----------------------------
# 8. Save final reference and reproducibility records
# -----------------------------

analysis_parameters <- data.frame(
  parameter = c(
    "SRA_runs", "CreateSeuratObject_min_cells",
    "CreateSeuratObject_min_features", "doublet_method", "SCT_vst_flavor",
    "SCT_method", "variable_features", "PCA_dimensions_used",
    "integration_method", "cluster_resolution", "random_seed"
  ),
  value = c(
    paste(sra_runs, collapse = ","), min_cells, min_features,
    "scDblFinder_per_library", "v2", "glmGamPoi", variable_features,
    integration_pcs, "HarmonyIntegration", cluster_resolution, random_seed
  ),
  stringsAsFactors = FALSE
)
write.csv(
  analysis_parameters,
  file.path(table_dir, "scRNA_reference_analysis_parameters.csv"),
  row.names = FALSE
)

software_packages <- c(
  "Seurat", "SeuratObject", "sctransform", "scDblFinder", "glmGamPoi", "harmony"
)
software_versions <- data.frame(
  software = c("R", software_packages),
  version = c(
    as.character(getRversion()),
    vapply(software_packages, function(package_name) {
      if (requireNamespace(package_name, quietly = TRUE)) {
        as.character(packageVersion(package_name))
      } else {
        "not installed"
      }
    }, character(1))
  ),
  stringsAsFactors = FALSE
)
write.csv(
  software_versions,
  file.path(table_dir, "scRNA_reference_software_versions.csv"),
  row.names = FALSE
)

cell_summary <- as.data.frame(table(
  SRA_run = sc_reference$SRA_run,
  harmony_cluster = sc_reference$harmony_clusters
))
write.csv(
  cell_summary,
  file.path(table_dir, "scRNA_reference_cells_by_library_and_cluster.csv"),
  row.names = FALSE
)

saveRDS(sc_reference, output_rds, compress = FALSE)

writeLines(
  capture.output(sessionInfo()),
  file.path(session_dir, "10_scRNA_reference_integration_sessionInfo.txt")
)

message("Maize scRNA-seq reference integration completed.")
message("Final Seurat object: ", output_rds)
message("Cells: ", ncol(sc_reference), "; genes: ", nrow(sc_reference))
message("Active identity: harmony_clusters")
message("Figures: ", figure_dir)
message("Tables: ", table_dir)
