# Monocle 3 pseudotime analysis of maize developing shoot domains (Figure 10C)
#
# Expected project structure:
# data/
# ├── processed/
# │   ├── UL01_seurat_v5.rds
# │   ├── UL02_seurat_v5.rds
# │   ├── ... 14 individual Seurat v5 objects
# │   ├── maize_shoot_14samples_SCT_harmony_seurat_v5.rds
# │   └── monocle3/                         # generated by this script
# └── metadata/
#     └── metadata.csv
#
# The curated metadata.csv is used to retain only unambiguous SAM, P1_P2, P3,
# P4, and P5 tissue spots. Each individual Seurat object is converted to a
# Monocle 3 cell_data_set, the 14 objects are combined once, and Monocle then
# performs PCA preprocessing and physical-section alignment. For exact Figure
# 10C reproduction, the Harmony UMAP from the processed combined Seurat object
# is transferred to Monocle before graph learning and pseudotime ordering from
# a SAM-enriched root principal node. Users can instead request a newly computed
# Monocle UMAP when adapting the workflow to another dataset.

suppressPackageStartupMessages({
  library(Seurat)
  library(monocle3)
  library(Matrix)
  library(SingleCellExperiment)
  library(SummarizedExperiment)
  library(dplyr)
  library(ggplot2)
})

# -----------------------------
# 1. Paths and analysis settings
# -----------------------------

find_project_root <- function(path = getwd()) {
  path <- normalizePath(path, winslash = "/", mustWork = TRUE)
  repeat {
    if (dir.exists(file.path(path, "data")) &&
        dir.exists(file.path(path, "scripts"))) {
      return(path)
    }
    parent <- dirname(path)
    if (identical(parent, path)) {
      stop("Project root not found. Start R in the repository or a subdirectory.")
    }
    path <- parent
  }
}

project_root <- find_project_root()
processed_dir <- file.path(project_root, "data", "processed")
metadata_file <- file.path(project_root, "data", "metadata", "metadata.csv")
combined_seurat_file <- file.path(
  processed_dir, "maize_shoot_14samples_SCT_harmony_seurat_v5.rds"
)

output_data_dir <- file.path(processed_dir, "monocle3")
output_table_dir <- file.path(
  project_root, "results", "tables", "09_monocle3_pseudotime"
)
output_figure_dir <- file.path(
  project_root, "results", "figures", "09_monocle3_pseudotime"
)
session_dir <- file.path(project_root, "results", "sessionInfo")

dir.create(output_data_dir, recursive = TRUE, showWarnings = FALSE)
dir.create(output_table_dir, recursive = TRUE, showWarnings = FALSE)
dir.create(output_figure_dir, recursive = TRUE, showWarnings = FALSE)
dir.create(session_dir, recursive = TRUE, showWarnings = FALSE)

sample_to_suffix <- c(
  UL01 = 1L,
  UL02 = 2L,
  UL04 = 3L,
  VR01 = 4L,
  VR02 = 5L,
  VR03 = 6L,
  VR04 = 7L,
  DQ01 = 8L,
  DQ02 = 9L,
  DQ03 = 10L,
  DQ04 = 11L,
  DQ06 = 12L,
  DQ07 = 13L,
  DQ08 = 14L
)

domain_levels <- c("SAM", "P1_P2", "P3", "P4", "P5")
domain_colors <- c(
  SAM = "#E41A1C",
  P1_P2 = "#F8766D",
  P3 = "#2CA25F",
  P4 = "#19BFC4",
  P5 = "#2C6DB2"
)

umi_cutoff <- 100
num_dim <- 100
# section_id uniquely identifies each physical section (for example UL01_S1).
# Do not use `section`, which contains repeated serial-position labels such as
# Section1 across different capture areas and may encode biological position.
alignment_column <- "section_id"
umap_n_neighbors <- 15L
umap_min_dist <- 0.1
random_seed <- 2026L
cores <- 1L

# TRUE reproduces the manuscript panel geometry by transferring umap_harmony
# from the combined Seurat object. Set FALSE to calculate a new Monocle UMAP
# from the section-aligned PCA coordinates for a new dataset.
use_seurat_harmony_umap <- TRUE
seurat_umap_reduction <- "umap_harmony"

# A single graph is learned across the five ordered developmental domains. This
# prevents cells in partitions lacking the SAM root from receiving infinite
# pseudotime. close_loop = FALSE retains a tree-like developmental trajectory.
use_partition_for_graph <- FALSE
close_loop <- FALSE

# -----------------------------
# 2. Helper functions
# -----------------------------

canonical_barcode <- function(barcode, sample_number) {
  barcode <- as.character(barcode)
  barcode <- sub("^[^_]+_(?=[ACGTN]+-[0-9]+)", "", barcode, perl = TRUE)
  barcode <- sub("_1_[0-9]+$", "", barcode)
  barcode <- sub("x$", "", barcode)
  ifelse(
    grepl("-[0-9]+$", barcode),
    paste0(barcode, "_1_", sample_number),
    paste0(barcode, "-1_1_", sample_number)
  )
}

read_curated_metadata <- function(path) {
  if (!file.exists(path)) stop("Metadata file not found: ", path)
  metadata <- read.csv(
    path,
    stringsAsFactors = FALSE,
    check.names = FALSE,
    colClasses = "character"
  )

  required <- c("Barcode", "sample_id", "domains", alignment_column)
  missing <- setdiff(required, colnames(metadata))
  if (length(missing) > 0L) {
    stop("metadata.csv is missing: ", paste(missing, collapse = ", "))
  }
  if (anyDuplicated(metadata$Barcode)) {
    stop("metadata.csv contains duplicated Barcode values.")
  }

  metadata <- metadata[
    metadata$sample_id %in% names(sample_to_suffix) &
      metadata$domains %in% domain_levels,
    ,
    drop = FALSE
  ]
  if (nrow(metadata) == 0L) {
    stop("No curated SAM/P1_P2/P3/P4/P5 spots were found in metadata.csv.")
  }

  rownames(metadata) <- metadata$Barcode
  metadata$sample_id <- factor(metadata$sample_id, levels = names(sample_to_suffix))
  metadata$domains <- factor(metadata$domains, levels = domain_levels, ordered = TRUE)
  metadata[[alignment_column]] <- factor(metadata[[alignment_column]])
  metadata
}

get_raw_counts <- function(seurat_object, sample_id) {
  # SummarizedExperiment also exports an Assays() accessor. Because this script
  # attaches both Seurat and Bioconductor packages, qualify all Seurat v5 assay
  # accessors to prevent dispatch to the incompatible S4 accessor.
  if (!"RNA" %in% SeuratObject::Assays(seurat_object)) {
    stop(sample_id, " does not contain an RNA assay.")
  }

  layer_names <- SeuratObject::Layers(seurat_object[["RNA"]])
  count_layers <- grep("^counts($|\\.)", layer_names, value = TRUE)
  if (length(count_layers) != 1L) {
    stop(
      sample_id, " must contain exactly one RNA counts layer; found: ",
      paste(count_layers, collapse = ", ")
    )
  }

  SeuratObject::LayerData(
    seurat_object,
    assay = "RNA",
    layer = count_layers
  )
}

seurat_sample_to_cds <- function(sample_id, sample_number, metadata) {
  input_file <- file.path(
    processed_dir, paste0(sample_id, "_seurat_v5.rds")
  )
  if (!file.exists(input_file)) stop("Missing Seurat RDS: ", input_file)

  message("Converting ", sample_id, " to a Monocle 3 cell_data_set")
  seurat_object <- readRDS(input_file)
  raw_counts <- get_raw_counts(seurat_object, sample_id)

  new_barcodes <- canonical_barcode(colnames(raw_counts), sample_number)
  if (anyDuplicated(new_barcodes)) {
    stop("Canonical barcode conversion produced duplicates for ", sample_id)
  }
  colnames(raw_counts) <- new_barcodes

  expected_spots <- rownames(metadata)[metadata$sample_id == sample_id]
  matched_spots <- intersect(expected_spots, colnames(raw_counts))
  missing_spots <- setdiff(expected_spots, colnames(raw_counts))

  if (length(matched_spots) == 0L) {
    stop(
      "No curated metadata barcodes matched the ", sample_id,
      " Seurat object after canonical barcode conversion."
    )
  }
  if (length(missing_spots) > 0L) {
    warning(
      sample_id, ": ", length(missing_spots), " of ", length(expected_spots),
      " curated spots were absent from the Seurat object."
    )
  }

  raw_counts <- raw_counts[, matched_spots, drop = FALSE]
  cell_metadata <- metadata[matched_spots, , drop = FALSE]
  gene_metadata <- data.frame(
    gene_short_name = rownames(raw_counts),
    row.names = rownames(raw_counts),
    stringsAsFactors = FALSE
  )

  cds <- new_cell_data_set(
    expression_data = raw_counts,
    cell_metadata = cell_metadata,
    gene_metadata = gene_metadata
  )

  rm(seurat_object, raw_counts)
  gc(verbose = FALSE)

  list(
    cds = cds,
    matching = data.frame(
      sample_id = sample_id,
      curated_metadata_spots = length(expected_spots),
      matched_spots = length(matched_spots),
      missing_spots = length(missing_spots),
      stringsAsFactors = FALSE
    )
  )
}

read_seurat_umap <- function(path, reduction) {
  if (!file.exists(path)) {
    stop("Combined Seurat object required for Figure 10C was not found: ", path)
  }

  message("Reading ", reduction, " coordinates for Figure 10C")
  seurat_object <- readRDS(path)
  if (!reduction %in% SeuratObject::Reductions(seurat_object)) {
    stop(
      "The combined Seurat object lacks reduction '", reduction,
      "'. Available reductions: ",
      paste(SeuratObject::Reductions(seurat_object), collapse = ", ")
    )
  }

  coordinates <- SeuratObject::Embeddings(
    seurat_object,
    reduction = reduction
  )
  if (ncol(coordinates) < 2L) {
    stop("The ", reduction, " reduction has fewer than two dimensions.")
  }
  coordinates <- coordinates[, 1:2, drop = FALSE]
  if (is.null(rownames(coordinates)) || anyDuplicated(rownames(coordinates))) {
    stop("The ", reduction, " reduction has missing or duplicated spot names.")
  }
  storage.mode(coordinates) <- "double"
  colnames(coordinates) <- c("UMAP_1", "UMAP_2")

  rm(seurat_object)
  gc(verbose = FALSE)
  coordinates
}

transfer_seurat_umap <- function(cds, coordinates) {
  missing_spots <- setdiff(colnames(cds), rownames(coordinates))
  if (length(missing_spots) > 0L) {
    stop(
      length(missing_spots),
      " retained Monocle spot(s) are absent from the Seurat UMAP; examples: ",
      paste(head(missing_spots, 5L), collapse = ", ")
    )
  }

  coordinates <- coordinates[colnames(cds), 1:2, drop = FALSE]
  stopifnot(identical(rownames(coordinates), colnames(cds)))
  SingleCellExperiment::reducedDims(cds)$UMAP <- coordinates
  cds
}

get_sam_root_principal_node <- function(cds) {
  sam_cells <- colnames(cds)[as.character(colData(cds)$domains) == "SAM"]
  if (length(sam_cells) == 0L) stop("No SAM spots are available for rooting.")

  closest_vertex <- cds@principal_graph_aux[["UMAP"]][[
    "pr_graph_cell_proj_closest_vertex"
  ]]
  closest_vertex <- as.matrix(closest_vertex[colnames(cds), , drop = FALSE])
  sam_vertices <- as.character(closest_vertex[sam_cells, 1L])
  most_frequent_vertex <- names(which.max(table(sam_vertices)))

  graph_vertex_names <- igraph::V(principal_graph(cds)[["UMAP"]])$name
  if (most_frequent_vertex %in% graph_vertex_names) {
    root_node <- most_frequent_vertex
  } else {
    root_index <- suppressWarnings(as.integer(most_frequent_vertex))
    if (is.na(root_index) || root_index < 1L || root_index > length(graph_vertex_names)) {
      stop("Could not map the SAM-enriched root to a principal graph node.")
    }
    root_node <- graph_vertex_names[root_index]
  }

  root_node
}

# -----------------------------
# 3. Convert and combine the 14 libraries
# -----------------------------

set.seed(random_seed)
metadata <- read_curated_metadata(metadata_file)

# Read and immediately release the large combined Seurat object before loading
# the 14 individual objects. Only its two-column UMAP matrix remains in memory.
seurat_umap_coordinates <- NULL
if (use_seurat_harmony_umap) {
  seurat_umap_coordinates <- read_seurat_umap(
    combined_seurat_file,
    seurat_umap_reduction
  )
}

conversion_results <- Map(
  f = function(sample_id, sample_number) {
    seurat_sample_to_cds(sample_id, sample_number, metadata)
  },
  sample_id = names(sample_to_suffix),
  sample_number = as.integer(sample_to_suffix)
)

cds_list <- lapply(conversion_results, `[[`, "cds")
names(cds_list) <- names(sample_to_suffix)
matching_summary <- bind_rows(lapply(conversion_results, `[[`, "matching"))

write.csv(
  matching_summary,
  file.path(output_table_dir, "Seurat_to_Monocle_barcode_matching.csv"),
  row.names = FALSE
)

cds <- combine_cds(
  cds_list,
  keep_all_genes = TRUE,
  # Barcodes were already made globally unique as <barcode>-1_1_<sample number>.
  # TRUE preserves those names. FALSE would append _<sample_id> and break the
  # authoritative metadata lookup below.
  cell_names_unique = TRUE,
  sample_col_name = "sample_id_from_combine",
  keep_reduced_dims = FALSE,
  verbose = TRUE
)

rm(cds_list, conversion_results)
gc(verbose = FALSE)

if (anyDuplicated(colnames(cds))) {
  stop("Duplicated spot names were found after combine_cds().")
}

missing_combined_metadata <- setdiff(colnames(cds), rownames(metadata))
if (length(missing_combined_metadata) > 0L) {
  stop(
    length(missing_combined_metadata),
    " combined spot barcode(s) are absent from metadata.csv; examples: ",
    paste(head(missing_combined_metadata, 5L), collapse = ", ")
  )
}

# Reapply the authoritative curated metadata after combination. This does not
# modify a Seurat active identity because the analysis is now within Monocle 3.
retained_metadata <- metadata[colnames(cds), , drop = FALSE]
for (column_name in colnames(retained_metadata)) {
  colData(cds)[[column_name]] <- retained_metadata[[column_name]]
}
colData(cds)$sample_id <- factor(
  colData(cds)$sample_id,
  levels = names(sample_to_suffix)
)
colData(cds)$domains <- factor(
  colData(cds)$domains,
  levels = domain_levels,
  ordered = TRUE
)
colData(cds)[[alignment_column]] <- factor(colData(cds)[[alignment_column]])

# Match the original load_cellranger_data(umi_cutoff = 100) criterion using the
# raw UMI counts transferred from the Seurat objects.
total_umi <- Matrix::colSums(SingleCellExperiment::counts(cds))
colData(cds)$total_umi <- as.numeric(total_umi)
keep_spots <- total_umi >= umi_cutoff
if (!any(keep_spots)) stop("No spots passed the UMI cutoff of ", umi_cutoff)
cds <- cds[, keep_spots]

cds <- detect_genes(cds)

write.csv(
  as.data.frame(table(
    sample_id = colData(cds)$sample_id,
    domains = colData(cds)$domains
  )),
  file.path(output_table_dir, "retained_spots_by_sample_and_domain.csv"),
  row.names = FALSE
)

# -----------------------------
# 4. Preprocess, align by section, and calculate UMAP
# -----------------------------

if (ncol(cds) <= num_dim || nrow(cds) <= num_dim) {
  stop(
    "The combined dataset is too small for num_dim = ", num_dim,
    ". Retained dimensions must be fewer than both spots and genes."
  )
}

cds <- preprocess_cds(
  cds,
  method = "PCA",
  num_dim = num_dim,
  norm_method = "log",
  verbose = TRUE
)

cds <- align_cds(
  cds,
  preprocess_method = "PCA",
  alignment_group = alignment_column,
  verbose = TRUE
)

if (use_seurat_harmony_umap) {
  # Manuscript reproduction: learn the Monocle trajectory on the same Harmony
  # UMAP geometry shown in Figure 10A and used in the original Figure 10C.
  cds <- transfer_seurat_umap(cds, seurat_umap_coordinates)
  rm(seurat_umap_coordinates)
  gc(verbose = FALSE)
} else {
  # General-use alternative: calculate an independent Monocle UMAP from the
  # section-aligned PCA coordinates.
  set.seed(random_seed)
  cds <- reduce_dimension(
    cds,
    reduction_method = "UMAP",
    preprocess_method = "Aligned",
    umap.metric = "cosine",
    umap.min_dist = umap_min_dist,
    umap.n_neighbors = umap_n_neighbors,
    cores = cores,
    verbose = TRUE
  )
}

cds <- cluster_cells(
  cds,
  reduction_method = "UMAP",
  random_seed = random_seed,
  verbose = TRUE
)

cds <- learn_graph(
  cds,
  use_partition = use_partition_for_graph,
  close_loop = close_loop,
  verbose = TRUE
)

# -----------------------------
# 5. Root with SAM and estimate pseudotime
# -----------------------------

sam_root_node <- get_sam_root_principal_node(cds)
cds <- order_cells(
  cds,
  reduction_method = "UMAP",
  root_pr_nodes = sam_root_node,
  verbose = TRUE
)

spot_pseudotime <- pseudotime(cds, reduction_method = "UMAP")
colData(cds)$pseudotime <- as.numeric(spot_pseudotime)

if (any(!is.finite(colData(cds)$pseudotime))) {
  warning(
    sum(!is.finite(colData(cds)$pseudotime)),
    " spots have infinite pseudotime and are not reachable from the SAM root."
  )
}

# -----------------------------
# 6. Export Figure 10C and analysis outputs
# -----------------------------

umap_coordinates <- as.data.frame(reducedDims(cds)$UMAP)
colnames(umap_coordinates)[1:2] <- c("UMAP_1", "UMAP_2")
umap_coordinates$Barcode <- rownames(umap_coordinates)

domain_label_positions <- umap_coordinates |>
  left_join(
    data.frame(
      Barcode = colnames(cds),
      domains = as.character(colData(cds)$domains),
      stringsAsFactors = FALSE
    ),
    by = "Barcode"
  ) |>
  group_by(domains) |>
  summarise(
    UMAP_1 = median(UMAP_1),
    UMAP_2 = median(UMAP_2),
    .groups = "drop"
  )

figure_10c <- plot_cells(
  cds,
  reduction_method = "UMAP",
  color_cells_by = "pseudotime",
  show_trajectory_graph = TRUE,
  trajectory_graph_color = "grey20",
  trajectory_graph_segment_size = 1.1,
  label_cell_groups = FALSE,
  label_branch_points = FALSE,
  label_roots = FALSE,
  label_leaves = FALSE,
  label_principal_points = TRUE,
  graph_label_size = 2.2,
  cell_size = 0.5,
  alpha = 0.9
) +
  scale_color_viridis_c(
    option = "turbo",
    direction = 1,
    name = "pseudotime"
  ) +
  geom_text(
    data = domain_label_positions,
    aes(x = UMAP_1, y = UMAP_2, label = domains),
    inherit.aes = FALSE,
    fontface = "bold",
    size = 4,
    color = "grey20"
  ) +
  labs(x = "UMAP-1", y = "UMAP-2") +
  theme_void(base_size = 11) +
  theme(
    legend.position = "right",
    plot.margin = margin(5.5, 5.5, 5.5, 5.5)
  )

ggsave(
  file.path(output_figure_dir, "Figure_10C_monocle3_pseudotime.png"),
  figure_10c,
  width = 6.2,
  height = 5.6,
  dpi = 300
)
ggsave(
  file.path(output_figure_dir, "Figure_10C_monocle3_pseudotime.pdf"),
  figure_10c,
  width = 6.2,
  height = 5.6
)

domain_plot <- plot_cells(
  cds,
  reduction_method = "UMAP",
  color_cells_by = "domains",
  show_trajectory_graph = TRUE,
  trajectory_graph_color = "grey25",
  trajectory_graph_segment_size = 0.9,
  label_cell_groups = FALSE,
  label_branch_points = FALSE,
  label_roots = FALSE,
  label_leaves = FALSE,
  cell_size = 0.45
) +
  scale_color_manual(values = domain_colors, drop = FALSE) +
  theme_classic(base_size = 11)

ggsave(
  file.path(output_figure_dir, "Monocle3_trajectory_by_domain.png"),
  domain_plot,
  width = 6.2,
  height = 5.6,
  dpi = 300
)

monocle_metadata <- as.data.frame(colData(cds))
monocle_metadata$Barcode <- NULL
output_metadata <- cbind(
  data.frame(
    Barcode = colnames(cds),
    monocle_metadata,
    check.names = FALSE
  ),
  umap_coordinates[colnames(cds), c("UMAP_1", "UMAP_2"), drop = FALSE]
)

write.csv(
  output_metadata,
  file.path(output_table_dir, "Monocle3_spot_pseudotime_and_metadata.csv"),
  row.names = FALSE
)

analysis_parameters <- data.frame(
  parameter = c(
    "n_libraries", "target_domains", "umi_cutoff", "num_dim",
    "alignment_column", "umap_n_neighbors", "umap_min_dist",
    "use_seurat_harmony_umap", "seurat_umap_reduction",
    "use_partition_for_graph", "close_loop", "SAM_root_principal_node",
    "random_seed", "cores"
  ),
  value = c(
    length(sample_to_suffix), paste(domain_levels, collapse = ","),
    umi_cutoff, num_dim, alignment_column, umap_n_neighbors, umap_min_dist,
    use_seurat_harmony_umap, seurat_umap_reduction,
    use_partition_for_graph, close_loop, sam_root_node, random_seed, cores
  ),
  stringsAsFactors = FALSE
)
write.csv(
  analysis_parameters,
  file.path(output_table_dir, "Monocle3_pseudotime_parameters.csv"),
  row.names = FALSE
)

saveRDS(
  cds,
  file.path(
    output_data_dir,
    "maize_shoot_SAM_P1_P2_P3_P4_P5_monocle3_pseudotime.rds"
  )
)

writeLines(
  capture.output(sessionInfo()),
  file.path(session_dir, "09_monocle3_pseudotime_sessionInfo.txt")
)

message("Monocle 3 pseudotime analysis completed.")
message("SAM root principal node: ", sam_root_node)
message("Figure: ", output_figure_dir)
message("Tables: ", output_table_dir)
message("Processed CDS: ", output_data_dir)
