#!/usr/bin/env python3
"""Merge Seurat and Velocyto data and compare stochastic/dynamical velocity.

Expected project structure
--------------------------
data/
├── raw/loom/
│   ├── XGE20_UL01_B73V5S210_short_MTCL.loom
│   ├── XGE20_UL02_B73V5S210_short_MTCL.loom
│   └── ... one loom file for each of the 14 samples
└── processed/RNA_velocity/seurat_export/
    ├── counts.mtx
    ├── features.csv
    ├── spot_metadata.csv
    ├── pca.csv
    └── umap.csv

The loom files must have been generated from the corresponding Space Ranger
outputs with Velocyto and the Zm-B73-REFERENCE-NAM-5.0 GTF. This program does
not run shell commands or Velocyto. It performs the Python/scVelo portion only.

Run scripts/R/08_RNA_velocity/01_export_Seurat_for_scVelo.R first. This program
reconstructs the Seurat data as AnnData, preserves its metadata/PCA/UMAP, joins
spliced and unspliced loom layers by exact spot and gene identifiers, and then
runs scVelo's stochastic and dynamical models on the same preprocessing,
neighborhood graph, moments, and Seurat UMAP. Only SAM, P1_P2, P3, P4, and P5
are retained.

Workflow references:
- Sam Morabito, "RNA velocity analysis with scVelo" (Seurat export/merge).
- scVelo dynamical-model documentation (filtering, moments, dynamics, velocity).
"""

from __future__ import annotations

import argparse
import importlib.metadata
import json
import logging
import re
import sys
import warnings
from pathlib import Path

import anndata as ad
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import scanpy as sc
import scvelo as scv
from scipy import sparse
from scipy.io import mmread


BIOLOGICAL_REPLICATE_TO_SUFFIX = {
    "UL01": 1,
    "UL02": 2,
    "UL04": 3,
    "VR01": 4,
    "VR02": 5,
    "VR03": 6,
    "VR04": 7,
    "DQ01": 8,
    "DQ02": 9,
    "DQ03": 10,
    "DQ04": 11,
    "DQ06": 12,
    "DQ07": 13,
    "DQ08": 14,
}

DOMAIN_ORDER = ["SAM", "P1_P2", "P3", "P4", "P5"]
DOMAIN_COLORS = {
    "SAM": "#E41A1C",
    "P1_P2": "#F8766D",
    "P3": "#2CA25F",
    "P4": "#19BFC4",
    "P5": "#2C6DB2",
}
VELOCITY_KEYS = {
    "stochastic": "velocity_stochastic",
    "dynamical": "velocity_dynamical",
}


def project_root_from_script() -> Path:
    """Return repository root for scripts/python/08_RNA_velocity/script.py."""
    return Path(__file__).resolve().parents[3]


def parse_arguments() -> argparse.Namespace:
    root = project_root_from_script()
    parser = argparse.ArgumentParser(
        description=(
            "Compare stochastic and dynamical scVelo analyses for maize "
            "developing leaves using identical preprocessing and coordinates."
        )
    )
    parser.add_argument("--project-root", type=Path, default=root)
    parser.add_argument(
        "--raw-dir",
        type=Path,
        default=None,
        help=(
            "Directory containing the loom files. Defaults to data/raw/loom, "
            "where the Zenodo record should be downloaded. "
            "Legacy per-sample subdirectories are also supported."
        ),
    )
    parser.add_argument(
        "--seurat-export-dir",
        type=Path,
        default=None,
        help=(
            "Directory generated by 01_export_Seurat_for_scVelo.R. Defaults "
            "to data/processed/RNA_velocity/seurat_export."
        ),
    )
    parser.add_argument("--processed-dir", type=Path, default=None)
    parser.add_argument("--figure-dir", type=Path, default=None)
    parser.add_argument("--table-dir", type=Path, default=None)
    parser.add_argument(
        "--min-shared-counts",
        type=int,
        default=20,
        help="Minimum combined spliced/unspliced counts used by scVelo gene filtering.",
    )
    parser.add_argument(
        "--n-top-genes",
        type=int,
        default=2000,
        help="Number of highly variable genes retained for velocity modeling.",
    )
    parser.add_argument(
        "--n-pcs",
        type=int,
        default=30,
        help="Number of PCs used for the neighborhood graph and moments.",
    )
    parser.add_argument(
        "--n-neighbors",
        type=int,
        default=30,
        help="Number of neighboring spots used to calculate moments.",
    )
    parser.add_argument(
        "--max-iter",
        type=int,
        default=20,
        help="Maximum EM iterations used by recover_dynamics().",
    )
    parser.add_argument(
        "--n-jobs",
        type=int,
        default=1,
        help="Parallel jobs for recover_dynamics(); use 1 for maximum portability.",
    )
    parser.add_argument(
        "--use-harmony",
        action="store_true",
        help=(
            "Optionally correct the PCA representation by biological replicate "
            "before moments. "
            "Off by default because Harmony was not specified for RNA velocity in "
            "the manuscript method."
        ),
    )
    parser.add_argument(
        "--recompute-pca",
        action="store_true",
        help=(
            "Recalculate PCA from the velocity-filtered genes. By default the "
            "PCA exported from Seurat is used for neighborhood moments."
        ),
    )
    parser.add_argument(
        "--diagnostic-unspliced-threshold",
        type=float,
        default=0.01,
        help=(
            "Report sample/domain groups with median unspliced fraction below this "
            "value. This diagnostic does not remove spots."
        ),
    )
    parser.add_argument(
        "--validate-files-only",
        action="store_true",
        help=(
            "Validate the 14 loom filenames and metadata coverage, then exit "
            "without loading loom matrices or running scVelo."
        ),
    )
    return parser.parse_args()


def configure_paths(args: argparse.Namespace) -> argparse.Namespace:
    root = args.project_root.resolve()
    args.project_root = root
    args.raw_dir = (args.raw_dir or root / "data" / "raw" / "loom").resolve()
    args.seurat_export_dir = (
        args.seurat_export_dir
        or root / "data" / "processed" / "RNA_velocity" / "seurat_export"
    ).resolve()
    args.processed_dir = (
        args.processed_dir or root / "data" / "processed" / "RNA_velocity"
    ).resolve()
    args.figure_dir = (
        args.figure_dir or root / "results" / "figures" / "08_RNA_velocity"
    ).resolve()
    args.table_dir = (
        args.table_dir or root / "results" / "tables" / "08_RNA_velocity"
    ).resolve()

    for directory in (args.processed_dir, args.figure_dir, args.table_dir):
        directory.mkdir(parents=True, exist_ok=True)
    return args


def configure_logging(table_dir: Path) -> None:
    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s [%(levelname)s] %(message)s",
        handlers=[
            logging.StreamHandler(sys.stdout),
            logging.FileHandler(table_dir / "RNA_velocity_run.log", mode="w"),
        ],
    )


def find_one_loom(raw_dir: Path, replicate_id: str) -> Path:
    """Find exactly one sample loom in the flat or legacy directory layout."""
    if not raw_dir.is_dir():
        raise FileNotFoundError(f"Loom directory not found: {raw_dir}")

    candidates: list[Path] = []

    # Canonical layout: all loom files are directly under data/raw/loom/.
    candidates.extend(
        path
        for path in raw_dir.glob("*.loom")
        if replicate_id.lower() in path.name.lower()
    )

    # Backward compatibility: allow data/raw/<sample>/.../*.loom or another
    # nested archive layout when --raw-dir points to a parent directory.
    if not candidates:
        candidates.extend(
            path
            for path in raw_dir.rglob("*.loom")
            if replicate_id.lower() in path.name.lower()
        )

    candidates = sorted({path.resolve() for path in candidates})
    if len(candidates) == 0:
        raise FileNotFoundError(
            f"No loom file found for {replicate_id} under {raw_dir}. "
            "Expected a filename containing the sample ID, such as "
            f"data/raw/loom/XGE20_{replicate_id}_B73V5S210_short_MTCL.loom."
        )
    if len(candidates) > 1:
        formatted = "\n  ".join(str(path) for path in candidates)
        raise RuntimeError(
            f"More than one loom file was found for {replicate_id}:\n  {formatted}\n"
            "Keep one loom per sample or place each sample in its own directory."
        )
    return candidates[0]


def canonical_barcode(raw_barcode: str, sample_number: int) -> str:
    """Convert a Velocyto barcode to the Seurat-v5 metadata barcode format."""
    barcode = str(raw_barcode).split(":")[-1].strip()

    # Velocyto loom files commonly end barcodes with "x" rather than "-1".
    barcode = re.sub(r"x$", "", barcode)

    # Remove a previously appended merged-object suffix if present.
    barcode = re.sub(r"_1_[0-9]+$", "", barcode)

    if not barcode.endswith("-1"):
        barcode = f"{barcode}-1"
    return f"{barcode}_1_{sample_number}"


def set_stable_gene_ids(loom: ad.AnnData, replicate_id: str) -> None:
    """Prefer stable gene accessions when Velocyto stored symbols as var_names."""
    for column in ("Accession", "gene_id", "Gene"):
        if column not in loom.var.columns:
            continue
        values = loom.var[column].astype(str)
        if values.notna().all() and values.is_unique:
            loom.var_names = values
            break

    if loom.var_names.has_duplicates:
        logging.warning(
            "%s contains duplicated gene identifiers; making them unique.", replicate_id
        )
        loom.var_names_make_unique()


def seurat_export_paths(export_dir: Path) -> dict[str, Path]:
    return {
        "counts": export_dir / "counts.mtx",
        "features": export_dir / "features.csv",
        "metadata": export_dir / "spot_metadata.csv",
        "pca": export_dir / "pca.csv",
        "umap": export_dir / "umap.csv",
    }


def read_seurat_export_metadata(export_dir: Path) -> pd.DataFrame:
    """Read and validate the lightweight part of the Seurat export."""
    paths = seurat_export_paths(export_dir)
    required_files = [
        paths["counts"],
        paths["features"],
        paths["metadata"],
        paths["umap"],
    ]
    missing_files = [str(path) for path in required_files if not path.is_file()]
    if missing_files:
        raise FileNotFoundError(
            "Missing Seurat export file(s):\n  " + "\n  ".join(missing_files)
        )
    empty_files = [str(path) for path in required_files if path.stat().st_size == 0]
    if empty_files:
        raise ValueError("Empty Seurat export file(s):\n  " + "\n  ".join(empty_files))

    metadata = pd.read_csv(paths["metadata"], dtype={"barcode": str})
    required_columns = {"barcode", "domains"}
    missing_columns = required_columns.difference(metadata.columns)
    if missing_columns:
        raise ValueError(
            "spot_metadata.csv is missing: " + ", ".join(sorted(missing_columns))
        )
    if metadata["barcode"].isna().any() or metadata["barcode"].duplicated().any():
        raise ValueError("spot_metadata.csv contains missing or duplicated barcodes.")

    # Metadata convention for the deposited embryonic-leaf subset:
    #   sample_id = physical section ID (for example UL01_S2)
    #   sample    = biological replicate/capture library (for example UL01)
    # New exports add explicit names. Older exports remain readable, but all
    # matching, QC, and optional Harmony operations below use the explicit
    # biological_replicate field rather than the ambiguous sample_id field.
    if "biological_replicate" in metadata.columns:
        biological_replicate = metadata["biological_replicate"].astype(str)
    elif "sample" in metadata.columns:
        biological_replicate = metadata["sample"].astype(str)
    elif "sample_id" in metadata.columns:
        biological_replicate = metadata["sample_id"].astype(str)
    else:
        raise ValueError(
            "spot_metadata.csv has no biological-replicate field. Expected "
            "`biological_replicate` or the source `sample` column."
        )
    if not biological_replicate.isin(BIOLOGICAL_REPLICATE_TO_SUFFIX).all():
        invalid = sorted(
            biological_replicate[
                ~biological_replicate.isin(BIOLOGICAL_REPLICATE_TO_SUFFIX)
            ].unique()
        )
        raise ValueError(
            "Biological-replicate values are not canonical UL01-DQ08 IDs: "
            + ", ".join(invalid[:10])
        )
    metadata["biological_replicate"] = biological_replicate

    if "section_id" not in metadata.columns:
        if "sample_id_original" in metadata.columns:
            metadata["section_id"] = metadata["sample_id_original"].astype(str)
        elif "sample_id" in metadata.columns:
            metadata["section_id"] = metadata["sample_id"].astype(str)
        else:
            metadata["section_id"] = "not_available"

    metadata = metadata.loc[
        metadata["domains"].isin(DOMAIN_ORDER)
        & metadata["biological_replicate"].isin(BIOLOGICAL_REPLICATE_TO_SUFFIX)
    ].copy()
    if metadata.empty:
        raise ValueError("The Seurat export contains no SAM/P1_P2/P3/P4/P5 spots.")
    metadata["domains"] = pd.Categorical(
        metadata["domains"], categories=DOMAIN_ORDER, ordered=True
    )
    logging.info(
        "Resolved metadata as %d biological replicates and %d physical sections; "
        "loom matching and QC use biological_replicate.",
        metadata["biological_replicate"].nunique(),
        metadata["section_id"].nunique(),
    )
    metadata = metadata.set_index("barcode", drop=False)
    return metadata


def read_exported_coordinates(
    path: Path, obs_names: pd.Index, minimum_dimensions: int
) -> np.ndarray:
    table = pd.read_csv(path, dtype={"barcode": str})
    if "barcode" not in table.columns:
        raise ValueError(f"{path.name} does not contain a barcode column.")
    if table["barcode"].duplicated().any():
        raise ValueError(f"{path.name} contains duplicated barcodes.")
    table = table.set_index("barcode")
    missing = obs_names.difference(table.index)
    if len(missing) > 0:
        raise ValueError(
            f"{path.name} is missing {len(missing)} exported spots; examples: "
            + ", ".join(missing[:5])
        )
    numeric = table.loc[obs_names].apply(pd.to_numeric, errors="coerce")
    if numeric.shape[1] < minimum_dimensions or not np.isfinite(numeric.to_numpy()).all():
        raise ValueError(
            f"{path.name} must contain at least {minimum_dimensions} finite dimensions."
        )
    return numeric.to_numpy(dtype=float)


def load_seurat_export(export_dir: Path) -> ad.AnnData:
    """Reconstruct AnnData from the sparse Seurat export."""
    paths = seurat_export_paths(export_dir)
    metadata = read_seurat_export_metadata(export_dir)

    features = pd.read_csv(paths["features"], dtype=str)
    if "gene_id" not in features.columns:
        raise ValueError("features.csv does not contain gene_id.")
    if features["gene_id"].isna().any() or features["gene_id"].duplicated().any():
        raise ValueError("features.csv contains missing or duplicated gene identifiers.")

    logging.info("Reading exported sparse RNA counts: %s", paths["counts"])
    counts = mmread(paths["counts"]).tocsr()
    expected_shape = (len(features), len(metadata))
    if counts.shape != expected_shape:
        raise ValueError(
            f"counts.mtx has shape {counts.shape}, expected genes x spots "
            f"{expected_shape}. Rerun the Seurat export without reordering files."
        )

    var = pd.DataFrame(index=pd.Index(features["gene_id"], name="gene_id"))
    adata = ad.AnnData(X=counts.T.tocsr(), obs=metadata.copy(), var=var)
    adata.obsm["X_umap"] = read_exported_coordinates(
        paths["umap"], adata.obs_names, minimum_dimensions=2
    )[:, :2]
    if paths["pca"].is_file() and paths["pca"].stat().st_size > 0:
        adata.obsm["X_pca"] = read_exported_coordinates(
            paths["pca"], adata.obs_names, minimum_dimensions=2
        )

    adata.uns["seurat_export"] = {
        "directory": str(export_dir),
        "counts": "RNA raw UMI counts",
        "umap_preserved": True,
        "pca_preserved": "X_pca" in adata.obsm,
    }
    logging.info(
        "Reconstructed Seurat AnnData: %d spots x %d genes",
        adata.n_obs,
        adata.n_vars,
    )
    return adata


def validate_input_files(raw_dir: Path, metadata: pd.DataFrame) -> None:
    """Validate the inexpensive parts of the input contract before analysis."""
    for replicate_id in BIOLOGICAL_REPLICATE_TO_SUFFIX:
        loom_path = find_one_loom(raw_dir, replicate_id)
        if loom_path.stat().st_size == 0:
            raise ValueError(f"Loom file is empty: {loom_path}")

        target_spots = int(
            (metadata["biological_replicate"] == replicate_id).sum()
        )
        if target_spots == 0:
            raise ValueError(
                "metadata.csv has no retained SAM/P1_P2/P3/P4/P5 spots for "
                f"biological replicate {replicate_id}."
            )
        logging.info(
            "Validated %s: %s (%d bytes; %d target metadata spots)",
            replicate_id,
            loom_path.name,
            loom_path.stat().st_size,
            target_spots,
        )


def load_and_subset_looms(
    raw_dir: Path, seurat_adata: ad.AnnData
) -> tuple[ad.AnnData, pd.DataFrame]:
    metadata = seurat_adata.obs
    looms: list[ad.AnnData] = []
    matching_rows: list[dict[str, object]] = []

    for replicate_id, sample_number in BIOLOGICAL_REPLICATE_TO_SUFFIX.items():
        loom_path = find_one_loom(raw_dir, replicate_id)
        logging.info("Loading biological replicate %s: %s", replicate_id, loom_path)
        # scVelo 0.3.x no longer exposes scv.read(). Scanpy's current loom
        # reader returns an AnnData object and preserves sparse count layers.
        loom = sc.read_loom(str(loom_path), sparse=True)

        required_layers = {"spliced", "unspliced"}
        missing_layers = required_layers.difference(loom.layers.keys())
        if missing_layers:
            raise ValueError(
                f"{loom_path} is missing layer(s): {', '.join(sorted(missing_layers))}"
            )

        set_stable_gene_ids(loom, replicate_id)
        original_spots = loom.n_obs
        loom.obs_names = [
            canonical_barcode(barcode, sample_number) for barcode in loom.obs_names
        ]
        if loom.obs_names.has_duplicates:
            raise ValueError(f"Canonical barcodes are duplicated in {loom_path}")

        expected = metadata.index[
            metadata["biological_replicate"].astype(str) == replicate_id
        ]
        matched = expected.intersection(loom.obs_names, sort=False)
        missing = expected.difference(loom.obs_names, sort=False)

        matching_rows.append(
            {
                "biological_replicate": replicate_id,
                "loom_file": str(loom_path),
                "spots_in_loom": original_spots,
                "target_metadata_spots": len(expected),
                "matched_spots": len(matched),
                "missing_target_spots": len(missing),
            }
        )

        if len(matched) == 0:
            raise ValueError(
                f"No {replicate_id} loom barcodes matched the curated metadata. "
                "Check the sample-to-suffix mapping and loom barcode format."
            )
        if len(missing) > 0:
            logging.warning(
                "%s: %d of %d target metadata spots were absent from the loom file.",
                replicate_id,
                len(missing),
                len(expected),
            )

        loom = loom[matched, :].copy()
        loom.obs["loom_biological_replicate"] = replicate_id
        looms.append(loom)

    combined = ad.concat(
        looms,
        axis=0,
        join="inner",
        merge="same",
        uns_merge="same",
        index_unique=None,
    )
    if combined.obs_names.has_duplicates:
        raise ValueError("Duplicated spot barcodes were found after loom concatenation.")

    ordered_spots = seurat_adata.obs_names.intersection(combined.obs_names, sort=False)
    missing_seurat_spots = seurat_adata.obs_names.difference(combined.obs_names, sort=False)
    if len(missing_seurat_spots) > 0:
        logging.warning(
            "%d of %d Seurat spots were absent from the loom files and will be removed.",
            len(missing_seurat_spots),
            seurat_adata.n_obs,
        )
    if len(ordered_spots) == 0:
        raise ValueError("No Seurat spots matched the combined loom data.")

    shared_genes = seurat_adata.var_names.intersection(combined.var_names, sort=False)
    if len(shared_genes) < 1000:
        raise ValueError(
            f"Only {len(shared_genes)} genes matched between Seurat and loom data. "
            "Check whether both inputs use the same Zm-B73-NAM-5.0 gene IDs."
        )
    logging.info(
        "Merging %d matched spots and %d shared genes from Seurat and loom data.",
        len(ordered_spots),
        len(shared_genes),
    )

    merged = seurat_adata[ordered_spots, shared_genes].copy()
    combined = combined[ordered_spots, shared_genes].copy()
    if not merged.obs_names.equals(combined.obs_names):
        raise ValueError("Seurat and loom spot order differs after matching.")
    if not merged.var_names.equals(combined.var_names):
        raise ValueError("Seurat and loom gene order differs after matching.")

    for layer_name in ("spliced", "unspliced", "ambiguous"):
        if layer_name in combined.layers:
            merged.layers[layer_name] = combined.layers[layer_name].copy()
    merged.obs["domains"] = pd.Categorical(
        merged.obs["domains"], categories=DOMAIN_ORDER, ordered=True
    )
    merged.uns["loom_merge"] = {
        "matched_spots": int(merged.n_obs),
        "missing_seurat_spots": int(len(missing_seurat_spots)),
        "shared_genes": int(merged.n_vars),
        "required_layers": ["spliced", "unspliced"],
    }

    return merged, pd.DataFrame(matching_rows)


def row_sum(matrix: object) -> np.ndarray:
    values = matrix.sum(axis=1)
    if sparse.issparse(values):
        values = values.A
    return np.asarray(values).ravel()


def add_unspliced_qc(adata: ad.AnnData) -> None:
    spliced = row_sum(adata.layers["spliced"])
    unspliced = row_sum(adata.layers["unspliced"])
    total = spliced + unspliced
    fraction = np.divide(
        unspliced,
        total,
        out=np.zeros_like(unspliced, dtype=float),
        where=total > 0,
    )
    adata.obs["spliced_counts"] = spliced
    adata.obs["unspliced_counts"] = unspliced
    adata.obs["unspliced_fraction"] = fraction


def export_qc(
    adata: ad.AnnData,
    matching: pd.DataFrame,
    table_dir: Path,
    diagnostic_threshold: float,
) -> None:
    matching.to_csv(table_dir / "loom_metadata_barcode_matching.csv", index=False)
    merge_summary = dict(adata.uns.get("loom_merge", {}))
    if merge_summary:
        merge_summary["required_layers"] = ",".join(
            merge_summary.get("required_layers", [])
        )
        pd.DataFrame([merge_summary]).to_csv(
            table_dir / "Seurat_loom_merge_summary.csv", index=False
        )

    qc_metadata = adata.obs.copy()
    # Count rows through a temporary index-derived field instead of depending
    # on whether the source metadata called the identifier Barcode or barcode.
    qc_metadata["_spot_id_for_count"] = adata.obs_names.astype(str)
    summary = (
        qc_metadata.groupby(["biological_replicate", "domains"], observed=True)
        .agg(
            n_spots=("_spot_id_for_count", "size"),
            median_spliced_counts=("spliced_counts", "median"),
            median_unspliced_counts=("unspliced_counts", "median"),
            median_unspliced_fraction=("unspliced_fraction", "median"),
        )
        .reset_index()
    )
    summary["low_unspliced_diagnostic"] = (
        summary["median_unspliced_fraction"] < diagnostic_threshold
    )
    summary.to_csv(table_dir / "spliced_unspliced_QC_by_sample_domain.csv", index=False)

    low_groups = summary.loc[summary["low_unspliced_diagnostic"]]
    if not low_groups.empty:
        logging.warning(
            "%d sample-domain group(s) have median unspliced fraction below %.3f. "
            "They were reported but not automatically removed.",
            len(low_groups),
            diagnostic_threshold,
        )


def use_existing_umap_if_available(adata: ad.AnnData) -> bool:
    if "X_umap" in adata.obsm:
        coordinates = np.asarray(adata.obsm["X_umap"])
        if coordinates.ndim == 2 and coordinates.shape[1] >= 2:
            if np.isfinite(coordinates[:, :2]).all():
                adata.obsm["X_umap"] = coordinates[:, :2]
                logging.info("Using UMAP coordinates exported from Seurat.")
                return True

    candidates = [
        ("UMAP_1", "UMAP_2"),
        ("umap_1", "umap_2"),
        ("harmonyUMAP_1", "harmonyUMAP_2"),
    ]
    for x_column, y_column in candidates:
        if x_column not in adata.obs or y_column not in adata.obs:
            continue
        coordinates = adata.obs[[x_column, y_column]].apply(pd.to_numeric, errors="coerce")
        if coordinates.notna().all().all():
            adata.obsm["X_umap"] = coordinates.to_numpy(dtype=float)
            logging.info("Using metadata UMAP coordinates: %s, %s", x_column, y_column)
            return True
    return False


def install_scvelo_numpy2_stochastic_compatibility() -> None:
    """Fix scVelo 0.3.4 scalar assignment under NumPy 2 without changing GLS.

    scVelo 0.3.4's default stochastic generalized least-squares branch assigns
    a one-element NumPy array directly to one scalar element of ``gamma``.
    NumPy 1.x accepted that implicit conversion; NumPy 2 raises
    ``ValueError: setting an array element with a sequence``. This local shim
    reproduces the same calculation and explicitly extracts that one scalar.
    It changes neither filtering nor the stochastic model and is installed
    only for the affected scVelo/NumPy combination.
    """
    scvelo_version = importlib.metadata.version("scvelo")
    numpy_major = int(np.__version__.split(".", maxsplit=1)[0])
    if scvelo_version != "0.3.4" or numpy_major < 2:
        return

    velocity_module = importlib.import_module("scvelo.tools.velocity")
    optimization_module = importlib.import_module("scvelo.tools.optimization")
    original_leastsq = velocity_module.leastsq_generalized
    if getattr(original_leastsq, "_maize_numpy2_compatible", False):
        return

    def leastsq_generalized_numpy2(
        x,
        y,
        x2,
        y2,
        res_std=None,
        res2_std=None,
        fit_offset=False,
        fit_offset2=False,
        perc=None,
    ):
        # The offset branches already unpack vectors into scalar values and do
        # not exhibit this NumPy-2 failure. Preserve their installed behavior.
        if fit_offset or fit_offset2:
            return original_leastsq(
                x,
                y,
                x2,
                y2,
                res_std,
                res2_std,
                fit_offset,
                fit_offset2,
                perc,
            )

        if perc is not None:
            if isinstance(perc, (list, tuple)):
                perc = perc[1]
            weights = sparse.csr_matrix(
                optimization_module.get_weight(x, y, perc=perc)
                | optimization_module.get_weight(x, perc=perc)
            ).astype(bool)
            x = weights.multiply(x).tocsr()
            y = weights.multiply(y).tocsr()

        _, n_vars = x.shape
        offset = np.zeros(n_vars, dtype="float32")
        offset_ss = np.zeros(n_vars, dtype="float32")
        gamma = np.ones(n_vars, dtype="float32")
        if res_std is None or res2_std is None:
            res_std = np.ones(n_vars)
            res2_std = np.ones(n_vars)

        with warnings.catch_warnings():
            warnings.simplefilter("ignore")
            x = np.vstack(
                (optimization_module.make_dense(x) / res_std, x2 / res2_std)
            )
            y = np.vstack(
                (optimization_module.make_dense(y) / res_std, y2 / res2_std)
            )

        for index in range(n_vars):
            design = np.c_[x[:, index]]
            solution = np.linalg.pinv(design.T.dot(design)).dot(
                design.T.dot(y[:, index])
            )
            gamma[index] = np.asarray(solution).reshape(-1)[0]

        gamma[np.isnan(gamma)] = 0
        return offset, offset_ss, gamma

    leastsq_generalized_numpy2._maize_numpy2_compatible = True
    velocity_module.leastsq_generalized = leastsq_generalized_numpy2
    logging.warning(
        "Applied the documented scVelo 0.3.4/NumPy 2 stochastic-GLS "
        "scalar-conversion compatibility fix."
    )


def preprocess_and_run_velocities(adata: ad.AnnData, args: argparse.Namespace) -> None:
    # scVelo 0.3.4 removed n_top_genes from filter_and_normalize(), although
    # older tutorials pass it to that convenience wrapper. Run the component
    # operations explicitly so the workflow is compatible with the installed
    # API and the numerical intent remains unchanged.
    scv.pp.filter_genes(
        adata,
        min_shared_counts=args.min_shared_counts,
    )
    scv.pp.normalize_per_cell(adata)
    sc.pp.log1p(adata)
    sc.pp.highly_variable_genes(
        adata,
        n_top_genes=min(args.n_top_genes, adata.n_vars),
        flavor="seurat",
        subset=True,
    )
    logging.info(
        "Retained %d highly variable genes after explicit scVelo/Scanpy preprocessing.",
        adata.n_vars,
    )

    exported_pcs = adata.obsm.get("X_pca")
    if exported_pcs is not None and not args.recompute_pca:
        n_pcs = min(args.n_pcs, exported_pcs.shape[1], adata.n_obs - 1)
    else:
        n_pcs = min(args.n_pcs, adata.n_obs - 1, adata.n_vars - 1)
    if n_pcs < 2:
        raise ValueError("Too few spots or genes remain for PCA and velocity analysis.")

    if exported_pcs is not None and not args.recompute_pca:
        adata.obsm["X_pca"] = np.asarray(exported_pcs)[:, :n_pcs]
        logging.info("Using %d PCA dimensions exported from Seurat.", n_pcs)
    else:
        # Recalculation is optional; the default follows the Seurat-to-AnnData
        # workflow in the supplied scVelo tutorial and preserves its PCA.
        sc.tl.pca(
            adata,
            n_comps=n_pcs,
            use_highly_variable=True,
            svd_solver="arpack",
            random_state=0,
        )
        logging.info("Recomputed %d PCA dimensions from velocity-filtered genes.", n_pcs)
    representation = "X_pca"

    if args.use_harmony:
        try:
            import scanpy.external as sce

            sce.pp.harmony_integrate(
                adata,
                key="biological_replicate",
                basis="X_pca",
                adjusted_basis="X_pca_harmony",
                random_state=0,
            )
        except ImportError as error:
            raise ImportError(
                "--use-harmony requires the optional harmonypy package."
            ) from error
        representation = "X_pca_harmony"

    scv.pp.moments(
        adata,
        n_neighbors=min(args.n_neighbors, adata.n_obs - 1),
        n_pcs=n_pcs if representation == "X_pca" else None,
        use_rep=representation,
    )

    if "X_umap" not in adata.obsm:
        sc.tl.umap(adata, random_state=0)

    # Calculate stochastic velocity first. Both models use the same filtered
    # genes, PCA, neighbors, moments, and UMAP; their velocity layers and
    # directed graphs are stored under separate keys.
    install_scvelo_numpy2_stochastic_compatibility()
    stochastic_vkey = VELOCITY_KEYS["stochastic"]
    scv.tl.velocity(
        adata,
        mode="stochastic",
        vkey=stochastic_vkey,
        filter_genes=False,
    )
    if stochastic_vkey not in adata.layers:
        raise RuntimeError("Stochastic velocity was not stored in AnnData.")
    scv.tl.velocity_graph(
        adata,
        vkey=stochastic_vkey,
        n_jobs=args.n_jobs,
    )
    scv.tl.velocity_confidence(adata, vkey=stochastic_vkey)
    if adata.uns.get(f"{stochastic_vkey}_params", {}).get("mode") != "stochastic":
        raise RuntimeError("scVelo did not retain the requested stochastic model.")
    logging.info("Completed stochastic velocity and its directed graph.")

    # Dynamical mode requires kinetic-parameter recovery before velocity.
    scv.tl.recover_dynamics(
        adata,
        n_top_genes=min(args.n_top_genes, adata.n_vars),
        max_iter=args.max_iter,
        n_jobs=args.n_jobs,
    )
    if "fit_alpha" not in adata.var:
        raise RuntimeError(
            "recover_dynamics() did not add fit_alpha; refusing a silent "
            "fallback to stochastic velocity."
        )

    dynamical_vkey = VELOCITY_KEYS["dynamical"]
    scv.tl.velocity(
        adata,
        mode="dynamical",
        vkey=dynamical_vkey,
        filter_genes=False,
    )
    if dynamical_vkey not in adata.layers:
        raise RuntimeError("Dynamical velocity was not stored in AnnData.")
    if adata.uns.get(f"{dynamical_vkey}_params", {}).get("mode") != "dynamical":
        raise RuntimeError(
            "scVelo did not retain the requested dynamical model; check "
            "recover_dynamics() output."
        )
    scv.tl.velocity_graph(
        adata,
        vkey=dynamical_vkey,
        n_jobs=args.n_jobs,
    )
    scv.tl.velocity_confidence(adata, vkey=dynamical_vkey)
    logging.info("Completed dynamical velocity and its directed graph.")


def save_current_figure(path: Path) -> None:
    figure = plt.gcf()
    figure.savefig(path, dpi=300, bbox_inches="tight", facecolor="white")
    plt.close(figure)


def generate_figures(adata: ad.AnnData, figure_dir: Path) -> None:
    palette = [DOMAIN_COLORS[domain] for domain in DOMAIN_ORDER]

    sc.pl.umap(
        adata,
        color="domains",
        palette=palette,
        frameon=False,
        show=False,
        title="Developing shoot domains",
    )
    save_current_figure(figure_dir / "Figure_10A_domains_UMAP.png")

    scv.pl.proportions(adata, groupby="domains", show=False)
    save_current_figure(figure_dir / "RNA_velocity_spliced_unspliced_proportions.png")

    for mode, vkey in VELOCITY_KEYS.items():
        model_label = f"{mode.title()} RNA velocity"

        scv.pl.velocity_embedding_grid(
            adata,
            basis="umap",
            vkey=vkey,
            color="domains",
            palette=palette,
            density=1.0,
            arrow_length=3,
            arrow_size=2,
            frameon=False,
            title=model_label,
            show=False,
        )
        save_current_figure(
            figure_dir / f"Figure_10B_scVelo_{mode}_velocity_grid.png"
        )

        scv.pl.velocity_embedding_stream(
            adata,
            basis="umap",
            vkey=vkey,
            color="domains",
            palette=palette,
            density=2,
            max_length=1,
            frameon=False,
            title=model_label,
            show=False,
        )
        save_current_figure(figure_dir / f"scVelo_{mode}_velocity_stream.png")

    # Create a publication-ready, directly comparable two-panel grid figure.
    comparison_figure, axes = plt.subplots(1, 2, figsize=(16, 7))
    for axis, (mode, vkey) in zip(axes, VELOCITY_KEYS.items()):
        scv.pl.velocity_embedding_grid(
            adata,
            basis="umap",
            vkey=vkey,
            color="domains",
            palette=palette,
            density=1.0,
            arrow_length=3,
            arrow_size=2,
            frameon=False,
            title=f"{mode.title()} RNA velocity",
            show=False,
            ax=axis,
        )
    comparison_figure.tight_layout()
    comparison_figure.savefig(
        figure_dir
        / "Figure_10B_scVelo_stochastic_vs_dynamical_velocity_grid.png",
        dpi=300,
        bbox_inches="tight",
        facecolor="white",
    )
    plt.close(comparison_figure)


def package_versions() -> dict[str, str]:
    packages = [
        "python",
        "anndata",
        "scanpy",
        "scvelo",
        "numpy",
        "pandas",
        "scipy",
        "matplotlib",
        "loompy",
    ]
    versions: dict[str, str] = {"python": sys.version.replace("\n", " ")}
    for package in packages[1:]:
        try:
            versions[package] = importlib.metadata.version(package)
        except importlib.metadata.PackageNotFoundError:
            versions[package] = "not installed"
    return versions


def main() -> None:
    args = configure_paths(parse_arguments())
    configure_logging(args.table_dir)

    logging.info("Project root: %s", args.project_root)
    logging.info("Raw loom directory: %s", args.raw_dir)
    logging.info("Seurat export directory: %s", args.seurat_export_dir)

    metadata = read_seurat_export_metadata(args.seurat_export_dir)
    if args.validate_files_only:
        validate_input_files(args.raw_dir, metadata)
        logging.info(
            "Seurat-export and file-level RNA-velocity validation completed successfully."
        )
        return

    seurat_adata = load_seurat_export(args.seurat_export_dir)
    seurat_checkpoint = (
        args.processed_dir / "maize_shoot_SAM_P1_P2_P3_P4_P5_Seurat_export.h5ad"
    )
    seurat_adata.write_h5ad(seurat_checkpoint, compression="gzip")
    logging.info("Seurat-to-AnnData checkpoint: %s", seurat_checkpoint)

    adata, matching = load_and_subset_looms(args.raw_dir, seurat_adata)
    del seurat_adata
    logging.info(
        "Combined Seurat/loom dataset before velocity preprocessing: %d spots x %d genes",
        adata.n_obs,
        adata.n_vars,
    )

    add_unspliced_qc(adata)
    export_qc(
        adata,
        matching,
        args.table_dir,
        args.diagnostic_unspliced_threshold,
    )

    used_existing_umap = use_existing_umap_if_available(adata)
    preprocess_and_run_velocities(adata, args)

    adata.uns["RNA_velocity_parameters"] = {
        "domains": DOMAIN_ORDER,
        "biological_replicates": list(BIOLOGICAL_REPLICATE_TO_SUFFIX),
        "min_shared_counts": args.min_shared_counts,
        "n_top_genes": args.n_top_genes,
        "n_pcs": args.n_pcs,
        "n_neighbors": args.n_neighbors,
        "max_iter": args.max_iter,
        "n_jobs": args.n_jobs,
        "velocity_modes": list(VELOCITY_KEYS),
        "velocity_keys": VELOCITY_KEYS,
        "comparison_design": (
            "Both models use the same filtered AnnData, PCA, neighbors, "
            "moments, and UMAP coordinates."
        ),
        "harmony_used": args.use_harmony,
        "recomputed_pca": args.recompute_pca,
        "precomputed_umap_used": used_existing_umap,
        "seurat_export_directory": str(args.seurat_export_dir),
    }

    output_h5ad = (
        args.processed_dir
        / "maize_shoot_SAM_P1_P2_P3_P4_P5_scvelo_stochastic_dynamical.h5ad"
    )
    adata.write_h5ad(output_h5ad, compression="gzip")
    adata.obs.to_csv(args.table_dir / "RNA_velocity_spot_metadata.csv")
    generate_figures(adata, args.figure_dir)

    with (args.table_dir / "python_package_versions.json").open("w", encoding="utf-8") as handle:
        json.dump(package_versions(), handle, indent=2)

    logging.info("RNA velocity analysis completed.")
    logging.info("Processed AnnData: %s", output_h5ad)
    logging.info("Figures: %s", args.figure_dir)
    logging.info("Tables and log: %s", args.table_dir)


if __name__ == "__main__":
    main()
